spring.application.name=ProyectoFinal
server.port= 8035

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Muestra las consultas SQL generadas por Hibernate en consola.
spring.jpa.show-sql=true 
# Especifica el driver JDBC (puede omitirse si el driver está en el classpath).
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# logging.file.name=logs/proyecto-universidad-ESTUDIANTE.log
# logging.level.root=INFO
# logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p)%clr([%t]){cyan} %clr(%c){yellow} - %m%n
# logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %5p [%t] %c - %m%n
# logging.logback.rollingpolicy.max-file-size=10MB
# logging.logback.rollingpolicy.total-size-cap=100MB

# spring.jackson.date-format=dd/MM/yyyy
# spring.jackson.serialization.write-dates-as-timestamps=false

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.secertkey=${JWT_SECRET}